export const CITY_STATE_MAP = {
  Agartala: "Tripura",
  Agra: "Uttar Pradesh",
  Ahmedabad: "Gujarat",
  Aizawl: "Mizoram",
  Ajmer: "Rajasthan",
  Alappuzha: "Kerala",
  Aligarh: "Uttar Pradesh",
  Allahabad: "Uttar Pradesh",
  Amravati: "Maharashtra",
  Amritsar: "Punjab",
  Aurangabad: "Maharashtra",
  Bengaluru: "Karnataka",
  Bhopal: "Madhya Pradesh",
  Bhubaneswar: "Odisha",
  Bikaner: "Rajasthan",
  Chandigarh: "Chandigarh",
  Chennai: "Tamil Nadu",
  Coimbatore: "Tamil Nadu",
  Cuttack: "Odisha",
  Dehradun: "Uttarakhand",
  Delhi: "Delhi (National Capital Territory of Delhi)",
  Dhanbad: "Jharkhand",
  Dibrugarh: "Assam",
  Dimapur: "Nagaland",
  Durgapur: "West Bengal",
  Ernakulam: "Kerala",
  Erode: "Tamil Nadu",
  Faridabad: "Haryana",
  Gandhinagar: "Gujarat",
  Gangtok: "Sikkim",
  Ghaziabad: "Uttar Pradesh",
  Goa: "Goa",
  Gorakhpur: "Uttar Pradesh",
  "Greater Noida": "Uttar Pradesh",
  Guntur: "Andhra Pradesh",
  Gurugram: "Haryana",
  Guwahati: "Assam",
  Gwalior: "Madhya Pradesh",
  Hubballi: "Karnataka",
  Hyderabad: "Telangana",
  Indore: "Madhya Pradesh",
  Itanagar: "Arunachal Pradesh",
  Jaipur: "Rajasthan",
  Jalandhar: "Punjab",
  Jammu: "Jammu and Kashmir",
  Jamnagar: "Gujarat",
  Jamshedpur: "Jharkhand",
  Jodhpur: "Rajasthan",
  Kanpur: "Uttar Pradesh",
  Kochi: "Kerala",
  Kohima: "Nagaland",
  Kolkata: "West Bengal",
  Kozhikode: "Kerala",
  Lucknow: "Uttar Pradesh",
  Ludhiana: "Punjab",
  Madurai: "Tamil Nadu",
  Mangaluru: "Karnataka",
  Meerut: "Uttar Pradesh",
  Mohali: "Punjab",
  Moradabad: "Uttar Pradesh",
  Mumbai: "Maharashtra",
  Mysuru: "Karnataka",
  Nagpur: "Maharashtra",
  Nashik: "Maharashtra",
  "Navi Mumbai": "Maharashtra",
  Noida: "Uttar Pradesh",
  Panaji: "Goa",
  Patna: "Bihar",
  "Pimpri Chinchwad": "Maharashtra",
  Prayagraj: "Uttar Pradesh",
  Pune: "Maharashtra",
  Raipur: "Chhattisgarh",
  Rajkot: "Gujarat",
  Ranchi: "Jharkhand",
  Rourkela: "Odisha",
  Shillong: "Meghalaya",
  Shimla: "Himachal Pradesh",
  Siliguri: "West Bengal",
  Srinagar: "Jammu and Kashmir",
  Surat: "Gujarat",
  Thane: "Maharashtra",
  Thiruvananthapuram: "Kerala",
  Thrissur: "Kerala",
  Tiruchirappalli: "Tamil Nadu",
  Tiruppur: "Tamil Nadu",
  Udaipur: "Rajasthan",
  Vadodara: "Gujarat",
  Varanasi: "Uttar Pradesh",
  Vijayawada: "Andhra Pradesh",
  Visakhapatnam: "Andhra Pradesh",
  Warangal: "Telangana",
};

export const CITY_OPTIONS = Object.keys(CITY_STATE_MAP).sort((a, b) => a.localeCompare(b));
